// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTvOIHnHEJ-bxxRxkzjUz58nV7TRa4XE',
    appId: '1:501561779332:web:9ffd4056116d879fc30ed1',
    messagingSenderId: '501561779332',
    projectId: 'recipes-6af77',
    authDomain: 'recipes-6af77.firebaseapp.com',
    storageBucket: 'recipes-6af77.appspot.com',
    measurementId: 'G-WPGVKSNTEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThci-ULBX1T80wPUdEw1RW1ChqhvOeDg',
    appId: '1:501561779332:android:4725047637c92fc3c30ed1',
    messagingSenderId: '501561779332',
    projectId: 'recipes-6af77',
    storageBucket: 'recipes-6af77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8CZgpfn-kmWsKrEhRaogcKLSLUq0rlM',
    appId: '1:501561779332:ios:a8efbe9b9ec97b12c30ed1',
    messagingSenderId: '501561779332',
    projectId: 'recipes-6af77',
    storageBucket: 'recipes-6af77.appspot.com',
    iosClientId: '501561779332-4nb7mm39dkcedfrkvvrh7iarfs7qcn7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8CZgpfn-kmWsKrEhRaogcKLSLUq0rlM',
    appId: '1:501561779332:ios:a8efbe9b9ec97b12c30ed1',
    messagingSenderId: '501561779332',
    projectId: 'recipes-6af77',
    storageBucket: 'recipes-6af77.appspot.com',
    iosClientId: '501561779332-4nb7mm39dkcedfrkvvrh7iarfs7qcn7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipes',
  );
}
